version: '3.8'


services:

  postgres:
    container_name: course-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9456:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: course-api
    build:
      context: .
      dockerfile: userapi/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  pg-data:
