---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - build-essential
      - python3-pip
      - python3-venv
      - git
    state: present 