name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # This is the action
        with:
          app_name: ${{secrets.HEROKU_APP_NAME}}
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: ${{secrets.HEROKU_EMAIL}}
          heroku_apps: '[{"imagename":"api","appname":"app-test","apptype":"web"},{"imagename":"postgres","appname":"app-test","apptype":"db"}]'
          docker_compose_file: 'docker-compose.yaml'
